# Generated by Django 6.0.6 on 2026-06-07 06:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=30)),
                ('slug', models.SlugField(unique=True)),
                ('country', models.CharField(max_length=3)),
                ('primary_color', models.CharField(max_length=7)),
                ('secondary_color', models.CharField(max_length=7)),
                ('fbref_id', models.CharField(max_length=8, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Era',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=9)),
                ('start_year', models.PositiveSmallIntegerField()),
                ('end_year', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['start_year'],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mode', models.CharField(choices=[('classic', 'Classic'), ('ball', 'Ball Knowledge')], default='classic', max_length=10)),
                ('lineup', models.JSONField()),
                ('score', models.FloatField(blank=True, null=True)),
                ('record', models.CharField(blank=True, max_length=4)),
                ('grade', models.CharField(blank=True, max_length=2)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=50)),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('CB', 'Center-back'), ('LB', 'Left-back'), ('RB', 'Right-back'), ('DM', 'Defensive Midfielder'), ('CM', 'Central Midfielder'), ('AM', 'Attacking Midfielder'), ('LW', 'Left Winger'), ('RW', 'Right Winger'), ('ST', 'Striker')], max_length=2)),
                ('foot', models.CharField(blank=True, choices=[('L', 'Left'), ('R', 'Right'), ('B', 'Both')], max_length=1)),
                ('fbref_id', models.CharField(max_length=8, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClubEra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ucl_seasons', models.PositiveSmallIntegerField(default=0)),
                ('ucl_games', models.PositiveSmallIntegerField(default=0)),
                ('best_stage', models.CharField(choices=[('champion', 'Champion'), ('final', 'Finalist'), ('semi', 'Semi-Finals'), ('quarter', 'Quarter-Finals'), ('r16', 'Round of 16'), ('playoffs', 'Knockout Playoffs'), ('group', 'Group Stage')], max_length=10)),
                ('ucl_stage_points', models.PositiveSmallIntegerField(default=0)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_eras', to='game.club')),
                ('era', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_eras', to='game.era')),
            ],
            options={
                'ordering': ['club__name', 'era__start_year'],
                'unique_together': {('club', 'era')},
            },
        ),
        migrations.CreateModel(
            name='PlayerEraStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, choices=[('GK', 'Goalkeeper'), ('CB', 'Center-back'), ('LB', 'Left-back'), ('RB', 'Right-back'), ('DM', 'Defensive Midfielder'), ('CM', 'Central Midfielder'), ('AM', 'Attacking Midfielder'), ('LW', 'Left Winger'), ('RW', 'Right Winger'), ('ST', 'Striker')], max_length=2)),
                ('appearances', models.PositiveSmallIntegerField(default=0)),
                ('minutes', models.PositiveIntegerField(default=0)),
                ('goals', models.PositiveSmallIntegerField(default=0)),
                ('assists', models.PositiveSmallIntegerField(default=0)),
                ('yellow_cards', models.PositiveSmallIntegerField(default=0)),
                ('red_cards', models.PositiveSmallIntegerField(default=0)),
                ('clean_sheets', models.PositiveSmallIntegerField(default=0)),
                ('best_ucl_stage', models.CharField(choices=[('champion', 'Champion'), ('final', 'Finalist'), ('semi', 'Semi-Finals'), ('quarter', 'Quarter-Finals'), ('r16', 'Round of 16'), ('playoffs', 'Knockout Playoffs'), ('group', 'Group Stage')], max_length=10)),
                ('ucl_stage_points', models.PositiveSmallIntegerField(default=0)),
                ('team_ucl_games', models.PositiveSmallIntegerField(default=0)),
                ('era_rating', models.FloatField(blank=True, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='era_stats', to='game.club')),
                ('era', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='game.era')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='era_stats', to='game.player')),
            ],
            options={
                'ordering': ['-era_rating'],
                'unique_together': {('player', 'club', 'era')},
            },
        ),
    ]
